apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: qt-1-job
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 2
      name: nginx
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - command:
                - sleep
                - 10m
              image: nginx:latest
              name: nginx
              resources:
                requests:
                  cpu: 1
                limits:
                  cpu: 1
          restartPolicy: Never
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: qt-fat-queue
spec:
  weight: 4
  reclaimable: false