apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: qt-small-queue
spec:
  weight: 1
  reclaimable: false
  capability:
    cpu: 4
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: qt-fat-queue
spec:
  weight: 4
  reclaimable: false
  capability:
    cpu: 4